// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6FdjgAyps8XDCSRfwRbJca
// Component: dgrRbg4850
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_veticus_lecznica.module.css"; // plasmic-import: 6FdjgAyps8XDCSRfwRbJca/projectcss
import * as sty from "./PlasmicMap.module.css"; // plasmic-import: dgrRbg4850/css

export type PlasmicMap__VariantMembers = {};

export type PlasmicMap__VariantsArgs = {};
type VariantPropType = keyof PlasmicMap__VariantsArgs;
export const PlasmicMap__VariantProps = new Array<VariantPropType>();

export type PlasmicMap__ArgsType = {};
type ArgPropType = keyof PlasmicMap__ArgsType;
export const PlasmicMap__ArgProps = new Array<ArgPropType>();

export type PlasmicMap__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultMapProps {
  className?: string;
}

function PlasmicMap__RenderFunc(props: {
  variants: PlasmicMap__VariantsArgs;
  args: PlasmicMap__ArgsType;
  overrides: PlasmicMap__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMap__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicMap__VariantsArgs;
  args?: PlasmicMap__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicMap__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicMap__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMap__ArgProps,
      internalVariantPropNames: PlasmicMap__VariantProps
    });

    return PlasmicMap__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMap";
  } else {
    func.displayName = `PlasmicMap.${nodeName}`;
  }
  return func;
}

export const PlasmicMap = Object.assign(
  // Top-level PlasmicMap renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicMap
    internalVariantProps: PlasmicMap__VariantProps,
    internalArgProps: PlasmicMap__ArgProps
  }
);

export default PlasmicMap;
/* prettier-ignore-end */
